@startuml
skinparam dpi 200
actor 사용자
participant AccountRestController
participant RegexHelper
participant MemberService
participant RestHelper

사용자 -> AccountRestController : idUniqueCheck(String userId, Member memberInfo)
AccountRestController -> RegexHelper : 유효성 검사
AccountRestController -> MemberService : isUniqueUserId(Member input)
AccountRestController -> RestHelper : sendJson()
AccountRestController --> 사용자 : JSON 응답
@enduml
