@startuml
skinparam dpi 200
title AccountController Class Diagram

class AccountController {
    + AccountController()
    + index() : String
    + join() : String
    + joinResult() : String
    + login() : String
    + findId() : String
    + resetPw() : String
    + out() : String
}

@enduml