@startuml
skinparam dpi 200

actor Actor as "사용자"
participant AccountController

Actor -> AccountController: GET /account/edit
activate AccountController
note right: @SessionCheckHelper(enable = true)
AccountController --> Actor: "account/edit" 뷰 반환
deactivate AccountController

@enduml
