@startuml
skinparam dpi 200

actor Actor as "사용자"
participant AccountController

Actor -> AccountController: GET / or /account
activate AccountController
AccountController --> Actor: "account/index" 뷰 반환
deactivate AccountController

@enduml
