@startuml
skinparam dpi 200

actor Actor as "사용자"
participant AccountController

Actor -> AccountController: GET /account/login
activate AccountController
note right: @SessionCheckHelper(enable = false)
AccountController --> Actor: "account/login" 뷰 반환
deactivate AccountController

@enduml
